//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Securibox.FacturX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Securibox.FacturX.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Factur_X_1_09_BASIC {
            get {
                object obj = ResourceManager.GetObject("Factur-X_1.09_BASIC", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string Factur_X_1_09_BASIC_codedb {
            get {
                return ResourceManager.GetString("Factur-X_1.09_BASIC_codedb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Factur_X_1_09_BASICWL {
            get {
                object obj = ResourceManager.GetObject("Factur-X_1.09_BASICWL", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string Factur_X_1_09_BASICWL_codedb {
            get {
                return ResourceManager.GetString("Factur-X_1.09_BASICWL_codedb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Factur_X_1_09_EN16931 {
            get {
                object obj = ResourceManager.GetObject("Factur-X_1.09_EN16931", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string Factur_X_1_09_EN16931_codedb {
            get {
                return ResourceManager.GetString("Factur-X_1.09_EN16931_codedb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Factur_X_1_09_EXTENDED {
            get {
                object obj = ResourceManager.GetObject("Factur-X_1.09_EXTENDED", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string Factur_X_1_09_EXTENDED_codedb {
            get {
                return ResourceManager.GetString("Factur-X_1.09_EXTENDED_codedb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Factur_X_1_09_MINIMUM {
            get {
                object obj = ResourceManager.GetObject("Factur-X_1.09_MINIMUM", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        public static string Factur_X_1_09_MINIMUM_codedb {
            get {
                return ResourceManager.GetString("Factur-X_1.09_MINIMUM_codedb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xpacket begin=&quot;\ufeff&quot; id=&quot;W5M0MpCehiHzreSzNTczkc9d&quot;?&gt;
        ///&lt;x:xmpmeta xmlns:x=&quot;adobe:ns:meta/&quot;&gt;
        ///  &lt;rdf:RDF xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;&gt;
        ///    &lt;rdf:Description xmlns:pdfaid=&quot;http://www.aiim.org/pdfa/ns/id/&quot; rdf:about=&quot;&quot;&gt;
        ///      &lt;pdfaid:part&gt;3&lt;/pdfaid:part&gt;
        ///      &lt;pdfaid:conformance&gt;B&lt;/pdfaid:conformance&gt;
        ///    &lt;/rdf:Description&gt;
        ///    &lt;rdf:Description xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; rdf:about=&quot;&quot;&gt;
        ///      &lt;dc:title&gt;
        ///        &lt;rdf:Alt&gt;
        ///          &lt;rdf:li xml:lang=&quot;x-default [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdfMetadataTemplate {
            get {
                return ResourceManager.GetString("PdfMetadataTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] sRGB_IEC61966_2_1 {
            get {
                object obj = ResourceManager.GetObject("sRGB_IEC61966_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
