on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#    - name: Verify commit exists in origin/main
#      run: |
#        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
#        git branch --remote --contains | grep origin/main
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ inputs.version }}
    - name: Test
      run: dotnet test --configuration Release --no-build /p:Version=${{ inputs.version }}
    - name: Pack
      run: dotnet pack --configuration Release --no-build /p:Version=${{ inputs.version }} --no-build --output .